# Generated by Django 3.0.5 on 2020-04-10 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'allergies',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('large_image', models.ImageField(upload_to='drink_large_image/%Y/%m/%d')),
                ('small_image', models.ImageField(upload_to='drink_small_image/%Y/%m/%d')),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100)),
                ('millimeter', models.IntegerField(default=0)),
                ('fluid_ounce', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'sizes',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('eng_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('calory', models.DecimalField(decimal_places=2, max_digits=5)),
                ('saturated_fat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sodium', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sugar', models.DecimalField(decimal_places=2, max_digits=5)),
                ('caffeine', models.DecimalField(decimal_places=2, max_digits=5)),
                ('allergy', models.ManyToManyField(to='drink.Allergy')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drink.Category')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drink.Image')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drink.Size')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Allergy_To_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drink.Allergy')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drink.Product')),
            ],
            options={
                'db_table': 'allergy_to_products',
            },
        ),
    ]
